import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Card from '../components/cards';
import {
  CodeTag, Container, Description, Main,
  Title
} from '../components/sharedstyles';
import handleLocaleChange from '../utils/localeChange';

export default function Home() {
  const { t } = useTranslation('common');
  const router = useRouter();

  return (
    <Container>
      <Head>
        <title>{t('welcome')} <a href="https://nextjs.org">Next.js! </a></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
      <select
        onChange={(event)=>handleLocaleChange(event, router)}
        value={router?.locale || 'ptBR'}>
        <option value="en">English</option>
        <option value="ptBR">Portugues</option>
      </select>
        <Title>
          {t('welcome')}
        </Title>

        <Description>
          Get started by editing
          <CodeTag>pages/index.tsx</CodeTag>
        </Description>

        <Card link='/about' name='About Page &rarr;' />
      </Main>
    </Container>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}
